### ISSUE TITLE
link to android app source

### ISSUE THREAD

**Issue by gorn** [increpare/toki-utala#5]
Please provide link to source of Android app. I have found it here snd it seems to be the same project https://play.google.com/store/apps/details?id=com.increpare.tokiutala

**Comment by increpare** [comment]
Hi!  Good suggestion.

However, I don’t think I can.  If I want the app to be made available to minors (which I do), all sites linked to must also be similarly age-rated.  I want the app to be available to minors - in the last version I stripped out external links to specifically enable that :( .   Here’s the kind of message people get back from google:

" App: First level links
The weblinks in your app are not consistent with our policy. For any link provided within the app, the content must have a rating of E or E10+ and be compliant with our global policies. To resolve this issue, please remove non-compliant links and/or remove any inappropriate content displayed on these linked pages. "

I strongly suspect github doesn’t have a formal content rating.

**Comment by gorn** [comment]
Could you at leaset provide section "Source" and mention, that source is available on github in increpare/toki-utala repository?
